/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/

var i=Object.defineProperty;var c=Object.getOwnPropertyDescriptor;var a=Object.getOwnPropertyNames;var m=Object.prototype.hasOwnProperty;var r=(o,e)=>{for(var n in e)i(o,n,{get:e[n],enumerable:!0})},w=(o,e,n,t)=>{if(e&&typeof e=="object"||typeof e=="function")for(let l of a(e))!m.call(o,l)&&l!==n&&i(o,l,{get:()=>e[l],enumerable:!(t=c(e,l))||t.enumerable});return o};var y=o=>w(i({},"__esModule",{value:!0}),o);var f={};r(f,{default:()=>s});module.exports=y(f);var d=require("obsidian"),s=class extends d.Plugin{async onload(){this.addRibbonIcon("refresh-cw","Sync Follow Builders",()=>{new d.Notice("Follow Builders Sync is not implemented yet.")}),this.addCommand({id:"sync-follow-builders-feeds",name:"Sync Follow Builders feeds",callback:()=>{new d.Notice("Follow Builders Sync is not implemented yet.")}})}};
